### ISSUE TITLE
Anki Error on Launching using Ubuntu 18.10

### ISSUE THREAD

**Issue by FunMyWay** [donnemartin/system-design-primer#235]
I'm using Ubuntu 18.10 on Lenovo Thinkpad:
I get this error right after the install using Ubuntu software install ....after installed ...when pressing <launch button>:
_____________________________________________________
Error during startup:
Traceback (most recent call last):
  File "/usr/share/anki/aqt/main.py", line 50, in __init__
    self.setupUI()
  File "/usr/share/anki/aqt/main.py", line 75, in setupUI
    self.setupMainWindow()
  File "/usr/share/anki/aqt/main.py", line 585, in setupMainWindow
    tweb = self.toolbarWeb = aqt.webview.AnkiWebView()
  File "/usr/share/anki/aqt/webview.py", line 114, in __init__
    self.focusProxy().installEventFilter(self)
AttributeError: 'NoneType' object has no attribute 'installEventFilter'
_____________________________________________________

Anki version:  2.1.0+dfsg-1
Updated: 11/17/2018
The error message won't reappear unless you uninstall and reboot O/S.  Any help is appreciated.  Thanks!
DJ

**Comment by jrrus** [comment]
I am running Ubuntu 19.10 on an HP Envy 8300.  I get the same message when I try to launch Anki.
Anki shows up in the System Monitor. If I use System Monitor to kill Anki, the same message is repeated when I try to start Anki again.

**Comment by jrrus** [comment]
sorry, that was a mistype.
I am running Ubuntu 18.10

**Comment by jrrus** [comment]
I loaded Ubuntu 18.10 on an HP touchscreen laptop and Anki starts and synchronizes with AnkiWeb on this system.
